export const msg_prof = [
  {
    name: "Jacquelyn Rogahn",
    creationDate: "03-28-2023 04:40:27 AM",
    desc: "Today, I woke up feeling a bit tired and groggy, probably because I didn't get enough sleep last night. Despite feeling a bit sluggish, I managed to push through and complete all my morning tasks. At work, I had a meeting with my team to discuss our progress on a new project we've been working on. We identified some areas where we can improve, and we made plans to address those issues in the coming days. After work, I went for a run in the park. The weather was perfect, and it felt great to get some fresh air and exercise. As I ran, I listened to a new podcast episode about personal finance, which gave me some useful insights about managing my money better. In the evening, I cooked dinner and caught up with a friend over the phone. We hadn't spoken in a while, so it was nice to catch up and hear about what's been going on in her life. Overall, it was a pretty productive and enjoyable day, despite feeling a bit tired in the morning. I'm looking forward to getting some good rest tonight and tackling whatever tomorrow brings.",
  },
  {
    name: "Marta Ritchie",
    creationDate: "03-28-2023 04:40:27 AM",
    desc: "Today, I woke up feeling a bit tired and groggy, probably because I didn't get enough sleep last night. Despite feeling a bit sluggish, I managed to push through and complete all my morning tasks. At work, I had a meeting with my team to discuss our progress on a new project we've been working on. We identified some areas where we can improve, and we made plans to address those issues in the coming days. After work, I went for a run in the park. The weather was perfect, and it felt great to get some fresh air and exercise. As I ran, I listened to a new podcast episode about personal finance, which gave me some useful insights about managing my money better. In the evening, I cooked dinner and caught up with a friend over the phone. We hadn't spoken in a while, so it was nice to catch up and hear about what's been going on in her life. Overall, it was a pretty productive and enjoyable day, despite feeling a bit tired in the morning. I'm looking forward to getting some good rest tonight and tackling whatever tomorrow brings.",
  },
  {
    name: "Timothy Mohr",
    creationDate: "03-28-2023 04:40:27 AM",
    desc: "Today, I woke up feeling a bit tired and groggy, probably because I didn't get enough sleep last night. Despite feeling a bit sluggish, I managed to push through and complete all my morning tasks. At work, I had a meeting with my team to discuss our progress on a new project we've been working on. We identified some areas where we can improve, and we made plans to address those issues in the coming days. After work, I went for a run in the park. The weather was perfect, and it felt great to get some fresh air and exercise. As I ran, I listened to a new podcast episode about personal finance, which gave me some useful insights about managing my money better. In the evening, I cooked dinner and caught up with a friend over the phone. We hadn't spoken in a while, so it was nice to catch up and hear about what's been going on in her life. Overall, it was a pretty productive and enjoyable day, despite feeling a bit tired in the morning. I'm looking forward to getting some good rest tonight and tackling whatever tomorrow brings.",
  },
];